language: node_js
service:
    - redis-server
env:
  global:
  - REDIS_SENTINEL_JQ='127.0.0.1:26379'
  - REDIS_SENTINEL_NAME_JQ='jobqueue01'
cache:
  directories:
    - node_modules
node_js:
  - "6.3"
before_script:
  - redis-server /etc/redis/redis.conf --port 6379
  - bash ./deploy/setupSentinel.sh
install:
  - npm install
script:
  - npm test
branches:
  only:
    - master
    - dev
notifications:
  email: false